### ISSUE TITLE
Error installing pry-byebug:

### ISSUE THREAD

**Issue by Kevinsillo** [teuton-software/teuton#1]
When I run `sudo rake gems` I get error in this gem.

> Building native extensions. This could take a while...
> ERROR:  Error installing pry-byebug:
>         ERROR: Failed to build gem native extension.
> 
>  current directory: /var/lib/gems/2.5.0/gems/byebug-10.0.2/ext/byebug
> /usr/bin/ruby2.5 -r ./siteconf20180926-22620-7ommdj.rb extconf.rb
> mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
> 
> extconf failed, exit code 1

**Comment by dvarrui** [comment]
rake debian #This install all required software for Debian OS
rake opensuse #This install all required software for OpenSUSE OS

Some gems (like pry-byebug) need to compile source code. So It's necesary to install: make, gcc ruby-dev and ssh before install gems.

**Comment by dvarrui** [comment]
INFORMATION
pry-byebug gem is a ruby utility that allow us to debug the source code. It's no necesary if you only want to run sysadmingame. But if you are developer and want to debug the code... pry-byebug will help you. ;-)

**Comment by Kevinsillo** [comment]
Thanks for the reply, nice work.

**Comment by dvarrui** [comment]
> rake -T (To see all options)
rake check     # Check installation
rake clean     # Clean temp files
rake debian    # Debian installation
rake default   # Default
rake gems      # Install gems
rake opensuse  # OpenSUSE installation
rake update    # Update project

Use "rake opensuse" to install software on openSUSE.
Use "rake debian" to install software on Debian.
