### ISSUE TITLE
Bad exit code when teuton upgrade fails

### ISSUE THREAD

**Issue by fvarrui** [teuton-software/teuton#22]
When I run `teuton upgrade` and it fails, exit code 0 is returned, which is wrong because it has to return other than 0:

```bash
$ teuton upgrade
error: no se puede abrir .git/FETCH_HEAD: Permiso denegado
$ echo $?
0
```

**Comment by dvarrui** [comment]
Try with:
cd teuton/dir
git pull
If works then "teuton update" will work too.

INFO: I had rename "teuton upgrade" to "teuton update".

**Comment by fvarrui** [comment]
I know that it fails; I did it intentionally .... but `teuton-panel` is not a fortune teller, and need the correct exit code in order to know if there was a problem when executing `teuton` command.

**Comment by fvarrui** [comment]
I did the following test and it worked as expected:
```
D:\Users\fvarrui\Documents\GitHub\teuton>teuton update
Already up to date.
[ OK ] teuton update

D:\Users\fvarrui\Documents\GitHub\teuton>echo %ERRORLEVEL%
0
```
Then I disabled network connection, so it couldn't connect to GitHub:
```
D:\Users\fvarrui\Documents\GitHub\teuton>teuton update
fatal: unable to access 'https://github.com/teuton-software/teuton.git/': Could not resolve host: github.com
[FAIL] teuton update

D:\Users\fvarrui\Documents\GitHub\teuton>echo %ERRORLEVEL%
1
```
And it returned an exit code different to zero.
