### ISSUE TITLE
moodle.csv and resume.txt/.json files are being overwritten

### ISSUE THREAD

**Issue by fvarrui** [teuton-software/teuton#35]
Each execution of **teuton** overwrites the `moodle.csv` and `resume.txt/.json` files, so if successive executions are carried out (skipping test cases) previous results are lost.

A possible solution would be to include the date and time of creation of those file as part of their names in (format `yyyyMMddHHmmss`), for example:
```
moodle-20201001162700.csv
resume-20201001162700.txt
resume-20201001162700.json
```
> If they were generated on 1st october 2020 at 16:27:00.

**Comment by dvarrui** [comment]
https://github.com/teuton-software/teuton/blob/master/docs/dsl/execution/export.md

Example:
start
  show
  export :preserve => true
end 

Setting ":preserve => true", will save every output files into timestamp directory.

**Comment by fvarrui** [comment]
Great! Thanks
