### ISSUE TITLE
Linux and Mac installation scripts' URL are broken in Wiki article

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#36]
Specifically, in https://github.com/teuton-software/teuton/wiki/Installation-using-scripts it's said to run this command in order to install Teuton in a Linux system acting as a T-Node:

`
wget -qO- https://raw.githubusercontent.com/teuton-software/teuton/master/bin/linux_t-node_install.sh | bash`

Which gives a 404 error.

The good link for Linux is this instead: https://raw.githubusercontent.com/teuton-software/teuton/master/install/linux/linux_t-node_install.sh

For Mac installation it's the same issue

Thanks

**Comment by dvarrui** [comment]
Hello @q2dg!

Until 2019 we used the wiki to post the documentation but from that date we have the documentation in the doc folder of the repository itself (https://github.com/teuton-software/teuton/blob/master/README.md#documentation)

It is best that we deactivate the wiki to avoid confusion.
 
Thank you very much for reporting the problem.
