### ISSUE TITLE
Please add Fedora to supported system in installer script

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#37]
I've just done:

```
sudo dnf install ruby
gem install teuton
```

...an that's all: Teuton is installed correctly and run flawessly. 

So this distributiont could be added to the official T-Node installation script

Thanks!

**Comment by q2dg** [comment]
In fact, the official S-Node installation script could be update too simply by adding a line to install required packages in Fedora. Specifically, you just should do...:

`sudo dnf install openssh-server sudo`

...and that's all: the rest of the script applies perfectly as is

**Comment by dvarrui** [comment]
I have modified these scripts with your contributions to take into account platforms that use the "dnf" command as a package manager.

* install/llinux/linux_s-node_install.sh
* install/llinux/linux_s-node-uninstall.sh
* install/llinux/linux_t-node-install.sh

It has been tested on a Fedora 38 MV.

Thank you very much for the contributions for the Fedora platform
