### ISSUE TITLE
"Create skeleton project" wiki's article is broken

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#38]
Specifically, in https://github.com/teuton-software/teuton/wiki/Create-skeleton-project is said that the command to create a skeleton project is `teuton create` where in fact is` teuton new`
Thanks

**Comment by q2dg** [comment]
https://github.com/teuton-software/teuton/wiki/Commands should be changed too

**Comment by q2dg** [comment]
Sorry, but there is the same problem between `teuton play foo` (old version) and `teuton run foo` (new version) in
https://github.com/teuton-software/teuton/wiki/Commands and
https://github.com/teuton-software/teuton/wiki/Run-a-Test-Unit pages

**Comment by dvarrui** [comment]
The Wiki documentation is outdated.
We are going to deactivate the wiki to avoid confusion.
The documentation is located in Markdown documents within the docs folder of the repository itself.

Thank you so much
