### ISSUE TITLE
Misleading error messages

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#39]
When running a non-existent verb (like `teuton blabla foo` for instance) or a non-existent challenge (like `teuton run as6j843df`), the error message is always the same: **"[ERROR[ .rb extension required!"** , which is a lot misleading. Please make Teuton distingish most error types to be able to show more according messages. Thanks!

**Comment by dvarrui** [comment]
What do you think if the following message is displayed?

```bash
❯ teuton run example/foo
[ERROR] Cannot find main file!
         /home/username/example/foo/start.rb
         or /home/username/example/foo.rb
```

**Comment by q2dg** [comment]
Yeah, for me it's enough!
Thanks!

What about when specifying an non-existent verb?

**Comment by dvarrui** [comment]
1) I change it. :-)

2) When the teuton command receives an action that does not exist, it assumes that the default action is "run" and what has been passed is the path to the test that you want to execute. So the following actions are equivalent:

```bash
teuton run example01
teuton example01
```

**Comment by q2dg** [comment]
Ah, ok, I understand. So I'll close the issue, then: for me it's perfect. Thanks a lot!!
