### ISSUE TITLE
Is there any alternative to not to have to set PermitRootLogin=yes in S-node configurations?

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#41]
It's ugly...
Thanks!

**Comment by dvarrui** [comment]
It's true!

In an educational environment and for student machines, it might work, but it is not a safe habit to allow root connections in this way on the SSH server.

To allow root access without enabling PermitRootLogin, it is best to use the root user SSH keys.
Configure /root/.ssh/authorized_keys file.
