### ISSUE TITLE
In order to be able to know how to run a first test, besides the DSL and command pages that are already published, there should be another page explaining config.yaml file's syntax

### ISSUE THREAD

**Issue by q2dg** [teuton-software/teuton#43]
Which are the supported keys and values?
Thanks

**Comment by dvarrui** [comment]
On this page https://github.com/teuton-software/teuton/tree/master/docs/learn#readme
there is a sequence of documents in increasing order of difficulty that try to explain how to use Teuton, both in the use of DSL and config.yaml configurations.

In each example, you learn something new about DSL and config.yaml

Most of the parameters within config.yam are defined by the user as needed. There are few parameters reserved for Teuton.

Parameters with a "tt_" prefix are the ones that are reserved. What do you suggest is to have a document with all the parameters reserved? tt_members, tt_moodle_id, tt_skip and tt_include?

**Comment by dvarrui** [comment]
The keys and values of the config.yaml file depend on the test creator.
Except by

- tt_members: Name of the student(s)
- tt_skip: true/false
- tt_moodle_id: the student's email address on the Moodle platform or their ID
- tt_include: Path of other configuration files to include

**Comment by q2dg** [comment]
Yes, thanks! Well, just indicating this information you have answered here should be sufficient. As it's already here it should be found by anyone, though maybe writting it somewhere else could help too. So I'll close this issue, if you don't mind

**Comment by q2dg** [comment]
Well, what I was looking for whas this list shown here: https://github.com/teuton-software/teuton/blob/master/docs/learn/03-remote_hosts.md Seeing them in nearly every example made me think they were (are?) predefined.

On the other hand, maybe the sentence "Label hostID identifies specific machine. Host information (ip, username, password, protocol) cames from config file" from https://github.com/teuton-software/teuton/blob/master/docs/dsl/run.md#remote-run needs some clarifications: I infer from examples that "hostID" is the portion before the "_" in "host1_username", "host1_password", etc keys but maybe it could be other things too.

Thanks

**Comment by dvarrui** [comment]
That's how it is

In config.yaml we will have the value of the IP and username of a computer that we will call "host1" for example.
Then the information is saved as:

```
host1_ip: 192.168.1.16
host1_username: root
```

These fields are the ones that are read when it is necessary to establish a connection with the remote computer "host1".
Instead of host1 you can put the label you prefer.
